import { Stock, Sector } from '@/types/stock';

// 더미 주식 데이터
export const mockStocks: Stock[] = [
  // IT/반도체
  { stock_code: '005930', stock_name: '삼성전자', market: 'KOSPI', sector: '반도체' },
  { stock_code: '000660', stock_name: 'SK하이닉스', market: 'KOSPI', sector: '반도체' },
  { stock_code: '042700', stock_name: '한미반도체', market: 'KOSDAQ', sector: '반도체' },
  { stock_code: '357780', stock_name: '솔브레인', market: 'KOSPI', sector: '반도체' },

  // IT/소프트웨어
  { stock_code: '035720', stock_name: '카카오', market: 'KOSPI', sector: 'IT서비스' },
  { stock_code: '035420', stock_name: 'NAVER', market: 'KOSPI', sector: 'IT서비스' },
  { stock_code: '376300', stock_name: '디어유', market: 'KOSDAQ', sector: 'IT서비스' },
  { stock_code: '293490', stock_name: '카카오게임즈', market: 'KOSPI', sector: 'IT서비스' },

  // 자동차
  { stock_code: '005380', stock_name: '현대차', market: 'KOSPI', sector: '자동차' },
  { stock_code: '000270', stock_name: '기아', market: 'KOSPI', sector: '자동차' },
  { stock_code: '012330', stock_name: '현대모비스', market: 'KOSPI', sector: '자동차부품' },
  { stock_code: '161390', stock_name: '한국타이어앤테크놀로지', market: 'KOSPI', sector: '자동차부품' },

  // 화학
  { stock_code: '051910', stock_name: 'LG화학', market: 'KOSPI', sector: '화학' },
  { stock_code: '096770', stock_name: 'SK이노베이션', market: 'KOSPI', sector: '화학' },
  { stock_code: '373220', stock_name: 'LG에너지솔루션', market: 'KOSPI', sector: '2차전지' },
  { stock_code: '006400', stock_name: '삼성SDI', market: 'KOSPI', sector: '2차전지' },

  // 금융
  { stock_code: '055550', stock_name: '신한지주', market: 'KOSPI', sector: '은행' },
  { stock_code: '105560', stock_name: 'KB금융', market: 'KOSPI', sector: '은행' },
  { stock_code: '086790', stock_name: '하나금융지주', market: 'KOSPI', sector: '은행' },
  { stock_code: '000810', stock_name: '삼성화재', market: 'KOSPI', sector: '보험' },

  // 바이오/제약
  { stock_code: '207940', stock_name: '삼성바이오로직스', market: 'KOSPI', sector: '바이오' },
  { stock_code: '068270', stock_name: '셀트리온', market: 'KOSPI', sector: '바이오' },
  { stock_code: '326030', stock_name: 'SK바이오팜', market: 'KOSPI', sector: '제약' },
  { stock_code: '196170', stock_name: '알테오젠', market: 'KOSDAQ', sector: '바이오' },

  // 엔터테인먼트
  { stock_code: '041510', stock_name: 'SM', market: 'KOSDAQ', sector: '엔터테인먼트' },
  { stock_code: '122870', stock_name: 'YG PLUS', market: 'KOSDAQ', sector: '엔터테인먼트' },
  { stock_code: '352820', stock_name: '하이브', market: 'KOSPI', sector: '엔터테인먼트' },

  // 유통
  { stock_code: '139480', stock_name: '이마트', market: 'KOSPI', sector: '유통' },
  { stock_code: '028260', stock_name: '삼성물산', market: 'KOSPI', sector: '유통' },
  { stock_code: '011200', stock_name: 'HMM', market: 'KOSPI', sector: '해운' },

  // 건설
  { stock_code: '000720', stock_name: '현대건설', market: 'KOSPI', sector: '건설' },
  { stock_code: '028050', stock_name: '삼성엔지니어링', market: 'KOSPI', sector: '건설' },
  { stock_code: '047040', stock_name: '대우건설', market: 'KOSPI', sector: '건설' },

  // 식품
  { stock_code: '097950', stock_name: 'CJ제일제당', market: 'KOSPI', sector: '식품' },
  { stock_code: '271560', stock_name: '오리온', market: 'KOSPI', sector: '식품' },
  { stock_code: '004370', stock_name: '농심', market: 'KOSPI', sector: '식품' },

  // 통신
  { stock_code: '030200', stock_name: 'KT', market: 'KOSPI', sector: '통신' },
  { stock_code: '017670', stock_name: 'SK텔레콤', market: 'KOSPI', sector: '통신' },
  { stock_code: '032640', stock_name: 'LG유플러스', market: 'KOSPI', sector: '통신' },
];

// 더미 섹터 데이터
export const mockSectors: Sector[] = [
  {
    id: 1,
    code: 'IT001',
    name: '반도체',
    market: 'KOSPI',
    category: 'IT',
    level: 1,
    stock_count: 45,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '반도체'),
  },
  {
    id: 2,
    code: 'IT002',
    name: 'IT서비스',
    market: 'KOSPI',
    category: 'IT',
    level: 1,
    stock_count: 38,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === 'IT서비스'),
  },
  {
    id: 3,
    code: 'AUTO001',
    name: '자동차',
    market: 'KOSPI',
    category: '제조',
    level: 1,
    stock_count: 28,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '자동차'),
  },
  {
    id: 4,
    code: 'AUTO002',
    name: '자동차부품',
    market: 'KOSPI',
    category: '제조',
    level: 1,
    stock_count: 52,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '자동차부품'),
  },
  {
    id: 5,
    code: 'CHEM001',
    name: '화학',
    market: 'KOSPI',
    category: '소재',
    level: 1,
    stock_count: 67,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '화학'),
  },
  {
    id: 6,
    code: 'BAT001',
    name: '2차전지',
    market: 'KOSPI',
    category: '소재',
    level: 1,
    stock_count: 125,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '2차전지'),
  },
  {
    id: 7,
    code: 'FIN001',
    name: '은행',
    market: 'KOSPI',
    category: '금융',
    level: 1,
    stock_count: 15,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '은행'),
  },
  {
    id: 8,
    code: 'FIN002',
    name: '보험',
    market: 'KOSPI',
    category: '금융',
    level: 1,
    stock_count: 12,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '보험'),
  },
  {
    id: 9,
    code: 'BIO001',
    name: '바이오',
    market: 'KOSPI',
    category: '헬스케어',
    level: 1,
    stock_count: 89,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '바이오'),
  },
  {
    id: 10,
    code: 'PHARM001',
    name: '제약',
    market: 'KOSPI',
    category: '헬스케어',
    level: 1,
    stock_count: 43,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '제약'),
  },
  {
    id: 11,
    code: 'ENT001',
    name: '엔터테인먼트',
    market: 'KOSDAQ',
    category: '서비스',
    level: 1,
    stock_count: 24,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '엔터테인먼트'),
  },
  {
    id: 12,
    code: 'RET001',
    name: '유통',
    market: 'KOSPI',
    category: '서비스',
    level: 1,
    stock_count: 31,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '유통'),
  },
  {
    id: 13,
    code: 'SHIP001',
    name: '해운',
    market: 'KOSPI',
    category: '서비스',
    level: 1,
    stock_count: 18,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '해운'),
  },
  {
    id: 14,
    code: 'CONST001',
    name: '건설',
    market: 'KOSPI',
    category: '제조',
    level: 1,
    stock_count: 56,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '건설'),
  },
  {
    id: 15,
    code: 'FOOD001',
    name: '식품',
    market: 'KOSPI',
    category: '제조',
    level: 1,
    stock_count: 37,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '식품'),
  },
  {
    id: 16,
    code: 'TEL001',
    name: '통신',
    market: 'KOSPI',
    category: '통신',
    level: 1,
    stock_count: 8,
    is_active: true,
    stocks: mockStocks.filter(s => s.sector === '통신'),
  },
  {
    id: 17,
    code: 'STEEL001',
    name: '철강',
    market: 'KOSPI',
    category: '소재',
    level: 1,
    stock_count: 42,
    is_active: true,
  },
  {
    id: 18,
    code: 'GAME001',
    name: '게임',
    market: 'KOSDAQ',
    category: 'IT',
    level: 1,
    stock_count: 55,
    is_active: true,
  },
  {
    id: 19,
    code: 'COSM001',
    name: '화장품',
    market: 'KOSDAQ',
    category: '제조',
    level: 1,
    stock_count: 29,
    is_active: true,
  },
  {
    id: 20,
    code: 'EDU001',
    name: '교육',
    market: 'KOSDAQ',
    category: '서비스',
    level: 1,
    stock_count: 16,
    is_active: true,
  },
];
